# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  #sonarcloud:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #    with:
  #      # Disabling shallow clone is recommended for improving relevancy of reporting
  #      fetch-depth: 0
  #  - name: SonarCloud Scan
  #    uses: sonarsource/sonarcloud-github-action@master
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:

    runs-on: ubuntu-latest
    
    # Service containers to run with container-job
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: jicc
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install PostgreSQL Client
      run: |
        sudo apt-get update
        sudo apt-get install --yes postgresql-client
    - name: Setup Tables
      run: |
        psql -h localhost -U postgres -d postgres -f psql.sql
        python3 Src/cold_start_database.py
        psql -h localhost -U postgres -d postgres -f psql_insert.sql 
      env: 
        PGPASSWORD: jicc
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Testing
      env: 
        ip: localhost 
      run: |
        # pytest --cov=./ --cov-report=xml --doctest-modules
        coverage run -m unittest discover -s Src
        coverage report -m
        coverage xml -i
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
